name: Bump Versions
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  bump:
    runs-on: [self-hosted, ci]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_HOME: /home/parth/lockbook-ci-cache/home
      CARGO_TARGET_DIR: /home/parth/lockbook-ci-cache/target
    steps:
      - uses: actions/checkout@v4
      - name: run bump script
        run: |
          cargo run -p releaser -- bump-versions ${{ github.event.inputs.bump_type }}
